/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tNrxEcW8E7v
 */
import { CardContent, CardFooter, Card } from "@/components/ui/card"

export function busness_showup() {
  return (
    (<Card className="w-[350px] mx-auto">
      <CardContent className="p-6">
        <div className="grid items-center gap-2">
          <div className="flex items-center gap-2">
            <div className="rounded-lg overflow-hidden w-10 h-10">
              <img
                alt="Company logo"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40" />
            </div>
            <div className="grid gap-1.5">
              <div className="text-sm font-medium leading-none">Acme Corporation</div>
              <div className="text-xs leading-none text-gray-500 dark:text-gray-400">We make everything</div>
            </div>
          </div>
          <div className="border-t w-full" />
          <div className="grid gap-0.5 text-sm">
            <div className="font-semibold">Alice Johnson</div>
            <div>Marketing Director</div>
          </div>
        </div>
      </CardContent>
      <CardFooter className="p-6 flex justify-center">
        <div className="grid gap-1.5 text-sm text-center">
          <div className="font-semibold">Contact</div>
          <div className="text-gray-500 dark:text-gray-400">+1 (123) 456-7890</div>
          <div className="text-gray-500 dark:text-gray-400">alice.johnson@example.com</div>
          <div className="text-gray-500 dark:text-gray-400">123 Market St, Pleasantville, NV</div>
          <div className="text-gray-500 dark:text-gray-400">acme.example.com</div>
        </div>
      </CardFooter>
    </Card>)
  );
}
