/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pWcHMMOCQRp
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function navbarhuhu() {
  return (
    (<header className="flex items-center h-14 px-4 md:px-6 w-full">
      <Link className="mr-6" href="#">
        <MountainIcon className="h-6 w-6" />
        <span className="sr-only">Acme Inc</span>
      </Link>
      <nav className="flex-1 hidden space-x-4 md:flex">
        <Link className="font-medium" href="#">
          Features
        </Link>
        <Link className="font-medium" href="#">
          Pricing
        </Link>
        <Link className="font-medium" href="#">
          Solutions
        </Link>
        <Link className="font-medium" href="#">
          Customers
        </Link>
        <Link className="font-medium" href="#">
          Resources
        </Link>
      </nav>
      <div className="flex-1 min-w-0 md:mx-4">
        <form className="w-full flex space-x-2">
          <Input
            className="flex-1 min-w-0 text-sm"
            placeholder="Enter your email"
            type="email" />
          <Button className="text-sm" type="submit">
            Sign Up
          </Button>
        </form>
      </div>
      <Link className="text-sm font-medium underline" href="#">
        Contact Sales
      </Link>
    </header>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
