/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RFyVIPBAa8J
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import React, { useState } from 'react';
import axios from 'axios';

export function register() {
  // State to store input values
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
  });

  // Handle input change
  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.id]: e.target.value });
  };

  // Handle form submission
  const handleSubmit = (e) => {
    e.preventDefault(); // Prevent default form submission behavior
  
    axios.post('http://localhost/api/register', formData)
      .then((response) => {
        console.log('Registration successful:', response.data); // Handle success
        // You can redirect or update state as needed here
        window.location.href = '/login';
      })
      .catch((error) => {
        console.error('Registration failed:', error); // Handle errors
      });
  };
  return (
    <form onSubmit={handleSubmit}>
      <Card className="w-full max-w-md mx-auto">
        <CardHeader className="flex flex-col items-center space-y-2">
          <h2 className="text-2xl font-bold">Get early access</h2>
          <p className="text-sm text-gray-500 dark:text-gray-400 text-center">
            Sign up to get notified when we launch our product
          </p>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Your name" required onChange={handleChange} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Your email" required type="email" onChange={handleChange} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input type="password" id="password" placeholder="Your password" required onChange={handleChange} />
          </div>
          <Button className="w-full" type="submit">Sign Up</Button>
        </CardContent>
      </Card>
    </form>
  );
}

export default register;
